In [1]:
import torch
import numpy as np
import networkx as nx
import random

In [2]:
import HccLinkage

In [3]:
d = np.ones((10,10)).astype('float64')

In [4]:
d += np.random.normal(scale = 0.1, size = d.shape)
d = d + d.T
np.fill_diagonal(d,0)
d 

array([[0.        , 1.86367359, 2.05348685, 2.13632513, 1.94238959,
        1.68365091, 1.95081013, 2.03267938, 1.82162143, 2.31069301],
       [1.86367359, 0.        , 2.06178573, 1.92809935, 1.90001582,
        2.26197915, 1.77462555, 1.8642567 , 2.10067551, 1.83683057],
       [2.05348685, 2.06178573, 0.        , 1.971824  , 1.95027783,
        2.04896231, 1.98204082, 2.19851481, 2.08822143, 1.92676264],
       [2.13632513, 1.92809935, 1.971824  , 0.        , 2.06716474,
        1.79261543, 1.87090615, 1.91846899, 1.86878102, 1.97069428],
       [1.94238959, 1.90001582, 1.95027783, 2.06716474, 0.        ,
        1.82111097, 2.08523981, 1.93631263, 1.97869463, 1.78030442],
       [1.68365091, 2.26197915, 2.04896231, 1.79261543, 1.82111097,
        0.        , 2.09125051, 1.93697904, 1.79343436, 2.07419407],
       [1.95081013, 1.77462555, 1.98204082, 1.87090615, 2.08523981,
        2.09125051, 0.        , 2.02285391, 1.91341462, 1.88078445],
       [2.03267938, 1.8642567 , 2.1985148

In [5]:
U = HccLinkage.HccLinkage(d)
U.learn_UM()
U.d_U

[5] [0] 1.6836509096889523
[9] [7] 1.7305705882868065
[6] [1] 1.7746255500095962
[8] [0, 5] 1.8216214254916157
[7, 9] [1, 6] 1.880784454398163
[4] [2] 1.95027782556708
[1, 6, 7, 9] [3] 1.9706942824228437
[1, 3, 6, 7, 9] [2, 4] 1.9820408222021586
[0, 5, 8] [1, 2, 3, 4, 6, 7, 9] 2.1006755075543357


tensor([[0.0000, 2.1007, 2.1007, 2.1007, 2.1007, 1.6837, 2.1007, 2.1007, 1.8216,
         2.1007],
        [2.1007, 0.0000, 1.9820, 1.9707, 1.9820, 2.1007, 1.7746, 1.8808, 2.1007,
         1.8808],
        [2.1007, 1.9820, 0.0000, 1.9820, 1.9503, 2.1007, 1.9820, 1.9820, 2.1007,
         1.9820],
        [2.1007, 1.9707, 1.9820, 0.0000, 1.9820, 2.1007, 1.9707, 1.9707, 2.1007,
         1.9707],
        [2.1007, 1.9820, 1.9503, 1.9820, 0.0000, 2.1007, 1.9820, 1.9820, 2.1007,
         1.9820],
        [1.6837, 2.1007, 2.1007, 2.1007, 2.1007, 0.0000, 2.1007, 2.1007, 1.8216,
         2.1007],
        [2.1007, 1.7746, 1.9820, 1.9707, 1.9820, 2.1007, 0.0000, 1.8808, 2.1007,
         1.8808],
        [2.1007, 1.8808, 1.9820, 1.9707, 1.9820, 2.1007, 1.8808, 0.0000, 2.1007,
         1.7306],
        [1.8216, 2.1007, 2.1007, 2.1007, 2.1007, 1.8216, 2.1007, 2.1007, 0.0000,
         2.1007],
        [2.1007, 1.8808, 1.9820, 1.9707, 1.9820, 2.1007, 1.8808, 1.7306, 2.1007,
         0.0000]], dtype=tor

In [6]:
U.S

tensor([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  3,  4,  2,  5,  7,
        10,  1], dtype=torch.int32)